const PATHS = {
    ADMIN_LOGIN: '/admin-login',
    CREATE_USER: '/user',
    GET_USERS: '/users',
    USER_LOGIN: '/user-login',
    GOOGLE_LOGIN: '/google-login',
    CREATE_CONTEST: '/contest',
    GET_CONTESTS: '/contests',
    ADD_IN_CONTEST: '/submission',
    GET_SUBMISSIONS: '/submissions',
    GET_USER_DETAIL: '/user',
    UPDATE_WINNER: '/submission-winner',
    GET_SUBMISSIONS_NY_CONTEST: '/submissions-by-contest',
    GET_SUBMISSIONS_BY_USER: '/submission-by-user',
    GET_ACTIVE_COMPETETION: '/contests-active',
    GET_SIGNED_URL: '/signed-url',
    SEND_RESET_LINK: '/reset-password',
    CHANGE_PASSWORD: '/change-password',
    SEND_OTP: '/send-otp',
    FORGOT_PASSWORD: '/forgot-password',
    VISIT_COUNTER: '/increment',
    CREATE_FEEDBACK: '/feedback',
    GET_FEEDBACKS: '/feedbacks'
}
export default PATHS;